name: creditcard_statement_note
description: A new Flutter project.

publish_to: "none"

# リリースビルド作成時にバージョンを上げる(x.x.x(バージョン名)+x(ビルド番号))
version: 1.0.5+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_device_type: ^0.4.0
  path_provider: ^2.1.0
  sqflite: ^2.3.0
  cupertino_icons: ^1.0.6
  uuid: ^4.0.0
  flutter_launcher_icons: ^0.14.0
  fluttertoast: ^8.2.0

flutter_icons:
  image_path: "lib/assets/icon.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
